language: ruby
rvm:
- 2.1.5
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: "aVXgNZMY/NAbrNtnpilEDDh9Aa12+0x1neHMe1Uw+T5K+dmRZbb8FvN68IZKP5P+ADrKiaSIs/UCU6ALYQFkAjHkmqfsgfVL5pSpMjHL4Fv/VHXAvu19tvkW1CoceeeI+oZ9tE1IBBLTtiIK7PfcuyO5/nNoufrQKUXHylDJUR0="
  app: crunchynutcornsnake
  on:
    repo: pikesley/crunch
