language: ruby
rvm:
- 2.1.5
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: ZFtSblaoZEiAg9RYgIWcNodKajLMfaXC80miESFixPpmi1MWIjgn8PXJ0/JNqumoITAmVznrygp8pE2lzfgfTVoY034RUsRjaf0s3k7T8k1Nw/bEfOI78ozSJHYhrU6mCdxqJae7LlpG/hNy2VwPscZlBRHZumOCgb1cwlLvJiM=
  app: crunchynutcornsnake
  on:
    repo: pikesley/crunch
