require 'date'
require 'dotenv'
require 'google_drive_v0'
require 'active_support/core_ext/integer/inflections'

require_relative 'crunch/meal'
require_relative 'crunch/date'
require_relative 'crunch/shed'
require_relative 'crunch/sheet'
require_relative 'crunch/length'
